"""Generate executive summaries and export reports for contracts.

Produces a due diligence memo format that lawyers actually use, with
critical/material findings separated and specific recommendations.
"""

import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.contract import Contract
from app.models.clause import Clause
from app.services.ai_service import get_completion

SUMMARY_SYSTEM_PROMPT = """You are a senior M&A attorney preparing a due diligence findings memo for a partner whose client is considering entering into or acquiring rights under this contract.

Write the memo in professional legal format using markdown. Structure it exactly as follows:

# Due Diligence Findings Memo

**Re:** [Contract title]
**Date:** [Today's date]
**Prepared by:** ClauseGuard AI Legal Analysis

---

## Executive Summary

[3-5 sentences: overall risk profile, the single most important issue, and whether the contract is acceptable as-is or requires negotiation before execution. Be direct — partners do not want hedging.]

## Deal Impact Assessment

[2-3 sentences on how the findings might affect deal terms, pricing, or the decision to proceed.]

---

## Critical Findings

[For each critical-risk clause, one bullet: **[Section/Type]** — [1 sentence on the issue] → **Recommended action:** [specific action]]

## Material Findings

[For each high-risk clause, one bullet: **[Section/Type]** — [1 sentence on the issue] → **Recommended action:** [specific action]]

---

## Standard Provisions

[1-2 sentences on provisions that are market-standard and acceptable as written.]

## Missing Protections

[Bullet list of standard protections absent from this contract, if any.]

## Recommended Next Steps

[Numbered list, highest priority first. Be specific — name the section and the exact ask.]

---
*This memo was generated by ClauseGuard AI. All findings should be reviewed by a licensed attorney before reliance.*"""


async def generate_summary_report(
    db: AsyncSession, contract_id: uuid.UUID
) -> str:
    """Generate a comprehensive due diligence memo for a contract."""
    contract_result = await db.execute(
        select(Contract).where(Contract.id == contract_id)
    )
    contract = contract_result.scalar_one_or_none()
    if not contract:
        raise ValueError(f"Contract {contract_id} not found")

    clause_result = await db.execute(
        select(Clause)
        .where(Clause.contract_id == contract_id)
        .order_by(Clause.risk_score.desc())
    )
    clauses = list(clause_result.scalars().all())

    risk_summary = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    critical_findings = []
    high_findings = []

    for clause in clauses:
        level = clause.risk_level or "low"
        if level in risk_summary:
            risk_summary[level] += 1

        heading = clause.section_heading or clause.clause_type or "Unknown Section"
        score_str = f"{clause.risk_score:.2f}" if clause.risk_score is not None else "N/A"
        explanation = clause.explanation or (clause.clause_text[:200] if clause.clause_text else "No text available.")
        suggestion = clause.suggestion or "Request revision."

        entry = (
            f"  - **{heading}** (score: {score_str}) — {explanation}\n"
            f"    → Suggestion: {suggestion}"
        )

        if level == "critical":
            critical_findings.append(entry)
        elif level == "high":
            high_findings.append(entry)

    parties_str = "Unknown"
    if contract.parties and isinstance(contract.parties, dict):
        names = contract.parties.get("names", [])
        parties_str = " and ".join(names) if names else "Unknown"
    elif isinstance(contract.parties, str):
        parties_str = contract.parties

    context = f"""CONTRACT ANALYSIS DATA

Contract: {contract.title or contract.original_filename}
Contract Type: {contract.contract_type or "Unknown"}
Parties: {parties_str}
Governing Law: {contract.governing_law or "Not specified"}
Effective Date: {contract.effective_date or "Not specified"}
Expiration Date: {contract.expiration_date or "Not specified"}
Overall Risk Score: {contract.overall_risk_score if contract.overall_risk_score is not None else "N/A"} / 1.00
Risk Level: {(contract.risk_level or "N/A").upper()}

RISK DISTRIBUTION
Critical: {risk_summary['critical']} clause(s)
High: {risk_summary['high']} clause(s)
Medium: {risk_summary['medium']} clause(s)
Low: {risk_summary['low']} clause(s)
Total analyzed: {len(clauses)}

CRITICAL RISK CLAUSES (require immediate attention before execution):
{chr(10).join(critical_findings) if critical_findings else "None identified."}

HIGH RISK CLAUSES (require negotiation before execution):
{chr(10).join(high_findings) if high_findings else "None identified."}

CONTRACT CONTEXT:
{contract.raw_text[:3000] if contract.raw_text else "Full text not available."}
"""

    report = await get_completion(
        system_prompt=SUMMARY_SYSTEM_PROMPT,
        user_prompt=context,
        temperature=0.2,
        max_tokens=4000,
    )

    contract.summary = report
    await db.flush()

    return report
